#!/bin/sh

if [ -z "$1" ]
then
	gcc -Wall -Werror -Wextra *.c -I$FT -L$FT -lft -fsanitize=address -g && ./a.out
else
	gcc -Wall -Werror -Wextra $@ -I$FT -L$FT -lft -fsanitize=address -g && ./a.out
fi

